// Actions for movies
export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST"
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS"
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE"
export const SELECT_MOVIE = "SELECT_MOVIE"
export const DESELECT_MOVIE = "DESELECT_MOVIE"
export const GET_SELECTED_MOVIES = "GET_SELECTED_MOVIES"
